# Generated by Django 3.1.1 on 2020-09-15 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aea6cae5-6255-4d96-84fa-4b55144d7e2d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
