# Generated by Django 3.1.1 on 2020-09-15 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200915_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4293da99-1e06-404e-8590-1704a3f83a95'), editable=False, primary_key=True, serialize=False),
        ),
    ]
