# Generated by Django 3.1.1 on 2020-09-15 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200915_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5b628ed-4700-4365-a22b-19de62c551b0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
